### ISSUE TITLE
Change DocBlock and Schema.org links from http:// to https://

### ISSUE THREAD

**Issue by christophherr** [Getbeans/Beans#288]
Moving this from PR #286 into its own issue. 

For reference:
https://github.com/Getbeans/Beans/pull/286#issuecomment-399790371
https://github.com/Getbeans/Beans/pull/286#issuecomment-399794481

Let's focus on DocBlocks and Schema.org links.

**Comment by ibes** [comment]
Done three pull requests

schema.org #290
docblocks #289
and mixed stuff #291

There are a couple of more http:// but I guess that are most areas where it makes sense.

Please check if the schema.org replacement in the tests are fine. 
I am not experienced enough to be sure about that. 
Tests still pass.

**Comment by hellofromtonya** [comment]
@ibes You missed one in the [`lib/templates/fragments/footer.php` file on Line 39](https://github.com/Getbeans/Beans/blob/development/lib/templates/fragments/footer.php#L39).

**Comment by christophherr** [comment]
@ibes When you are fixing the one Tonya mentioned, you can include this one, too: https://github.com/Getbeans/Beans/commit/20182877c4e0decff2714baae7196e37a39d5d81#r29478695

**Comment by ibes** [comment]
Have found even two more in tests.
